### ISSUE TITLE
大神你好，请问为什么WORD文件不支持中文名？用中文名您的程序就报错。能修正这个问题吗？或者给个提示。

### ISSUE THREAD

**Issue by welon2005** [marx-yu/WopiHost#6]

**Comment by ldybyz** [comment]
我也遇到这个问题，目前解决的方法是把文件名和一个guid一一对应，访问路径的时候使用guid,wopihost中根据guid获取路径

**Comment by welon2005** [comment]
原来中文名需要encode下

**Comment by marx-yu** [comment]
> 原来中文名需要encode下
已增加支持
但也需要对query参数Wopisrc的值使用urlencode
