### ISSUE TITLE
关于修订模式

### ISSUE THREAD

**Issue by FCIron** [marx-yu/WopiHost#8]
大神我想一下wopi协议支持在线编辑的时候默认以没修订模式打开吗

**Comment by ztwz** [comment]
请问怎么用这个WopiHost代码呀？我跑起来只有一个命令窗口，但office调用不出来呀，office online我已经搭建好了，但使用http://[owas.domain]/we/WordEditorFrame.aspx?WOPISrc=http%3a%2f%2flocalhost%3a8080%2fwopi%2ffiles%2fword.docx&access_token=[token]&ui=zh-CN
方式连接不上office online呀。

**Comment by marx-yu** [comment]
> 请问怎么用这个WopiHost代码呀？我跑起来只有一个命令窗口，但office调用不出来呀，office online我已经搭建好了，但使用http://[owas.domain]/we/WordEditorFrame.aspx?WOPISrc=http%3a%2f%2flocalhost%3a8080%2fwopi%2ffiles%2fword.docx&access_token=[token]&ui=zh-CN
> 方式连接不上office online呀。
owas.domain -> 替换为office online服务的地址；
http%3a%2f%2flocalhost%3a8080%2fwopi%2ffiles%2fword.docx 是http://localhost:8080/wopi/files/word.docx的urlencode，要把其中的localhost:8080替换为wopihost服务的地址，即这个代码仓库启动的服务

**Comment by marx-yu** [comment]
> 请问怎么用这个WopiHost代码呀？我跑起来只有一个命令窗口，但office调用不出来呀，office online我已经搭建好了，但使用http://[owas.domain]/we/WordEditorFrame.aspx?WOPISrc=http%3a%2f%2flocalhost%3a8080%2fwopi%2ffiles%2fword.docx&access_token=[token]&ui=zh-CN
> 方式连接不上office online呀。

是的

**Comment by marx-yu** [comment]
已增加详细使用说明
